SHELL := /bin/bash

.PHONY: launch help

launch:
	@echo "Running EC2 launch script..."
	@bash launch_ec2.sh

help:
	@echo "Makefile for AWS EC2 operations"
	@echo ""
	@echo "Usage:"
	@echo "  make launch    - Launch a new EC2 instance based on launch_ec2.sh"
	@echo "  make help      - Show this help message" 